In [1]:
import pandas as pd

# Read the cardiovascular disease menu analysis file
cardiovascular = pd.read_csv('cardiovascular disease_menu_analysis.csv')

In [2]:
cardiovascular.head(5)

,menu_title,positive,negative,very_negative,neutral,reasoning
0,Easy Chicken Fajita Marinade,6,2,0,0,honey (negative): A form of added sugar; high ...
1,Boneless Buffalo Wings,6,3,2,0,hot pepper sauce (negative): Typically very hi...
2,Vietnamese Aromatic Lamb Chops,8,2,1,0,lime wedge (positive): A whole fruit source of...
3,Joy's Green Banana Salad,8,0,3,0,"banana (positive): Very high in potassium, a k..."
4,Danish Christmas Red Cabbage,2,0,2,0,red cabbage (positive): High in fiber and hear...

In [3]:
cardiovascular.columns = [
    f"{col}-cardiovascular" if col in ["positive", "negative", "very_negative", "neutral", "reasoning"] else col
    for col in cardiovascular.columns
]

In [4]:
cardiovascular.head(5)

,menu_title,positive-cardiovascular,negative-cardiovascular,very_negative-cardiovascular,neutral-cardiovascular,reasoning-cardiovascular
0,Easy Chicken Fajita Marinade,6,2,0,0,honey (negative): A form of added sugar; high ...
1,Boneless Buffalo Wings,6,3,2,0,hot pepper sauce (negative): Typically very hi...
2,Vietnamese Aromatic Lamb Chops,8,2,1,0,lime wedge (positive): A whole fruit source of...
3,Joy's Green Banana Salad,8,0,3,0,"banana (positive): Very high in potassium, a k..."
4,Danish Christmas Red Cabbage,2,0,2,0,red cabbage (positive): High in fiber and hear...

In [5]:
kidney = pd.read_csv('kidney disease_menu_analysis.csv')

kidney.head(5)

,menu_title,positive,negative,very_negative,neutral,reasoning
0,Easy Chicken Fajita Marinade,3,2,0,0,honey (negative): A source of sugar and potass...
1,Boneless Buffalo Wings,4,4,2,0,hot pepper sauce (very negative): Typically ex...
2,Vietnamese Aromatic Lamb Chops,5,2,1,0,garlic (positive): Excellent for adding flavor...
3,Joy's Green Banana Salad,4,4,3,0,banana (very negative): Famously high in potas...
4,Danish Christmas Red Cabbage,3,1,1,0,red cabbage (positive): A low-potassium vegeta...

In [6]:
kidney.columns = [
    f"{col}-kidney" if col in ["positive", "negative", "very_negative", "neutral", "reasoning"] else col
    for col in kidney.columns
]

In [7]:
kidney.head(5)

,menu_title,positive-kidney,negative-kidney,very_negative-kidney,neutral-kidney,reasoning-kidney
0,Easy Chicken Fajita Marinade,3,2,0,0,honey (negative): A source of sugar and potass...
1,Boneless Buffalo Wings,4,4,2,0,hot pepper sauce (very negative): Typically ex...
2,Vietnamese Aromatic Lamb Chops,5,2,1,0,garlic (positive): Excellent for adding flavor...
3,Joy's Green Banana Salad,4,4,3,0,banana (very negative): Famously high in potas...
4,Danish Christmas Red Cabbage,3,1,1,0,red cabbage (positive): A low-potassium vegeta...

In [8]:
diabetes = pd.read_csv('diabetes_menu_analysis.csv')

diabetes.head(5)

,menu_title,positive,negative,very_negative,neutral,reasoning
0,Easy Chicken Fajita Marinade,4,0,1,0,honey (very negative): A form of simple sugar ...
1,Boneless Buffalo Wings,4,3,2,0,hot pepper sauce (negative): Often very high i...
2,Vietnamese Aromatic Lamb Chops,7,1,1,0,garlic (positive): May improve cardiovascular ...
3,Joy's Green Banana Salad,7,2,2,0,banana (negative): Higher in sugar and carbohy...
4,Danish Christmas Red Cabbage,3,1,1,0,"red cabbage (positive): A low-carbohydrate, hi..."

In [9]:
diabetes.columns = [
    f"{col}-diabetes" if col in ["positive", "negative", "very_negative", "neutral", "reasoning"] else col
    for col in diabetes.columns
]

In [10]:
diabetes.head(5)

,menu_title,positive-diabetes,negative-diabetes,very_negative-diabetes,neutral-diabetes,reasoning-diabetes
0,Easy Chicken Fajita Marinade,4,0,1,0,honey (very negative): A form of simple sugar ...
1,Boneless Buffalo Wings,4,3,2,0,hot pepper sauce (negative): Often very high i...
2,Vietnamese Aromatic Lamb Chops,7,1,1,0,garlic (positive): May improve cardiovascular ...
3,Joy's Green Banana Salad,7,2,2,0,banana (negative): Higher in sugar and carbohy...
4,Danish Christmas Red Cabbage,3,1,1,0,"red cabbage (positive): A low-carbohydrate, hi..."

In [11]:
len(cardiovascular)

1708

In [12]:
len(kidney)

1708

In [13]:
len(diabetes)

1708

In [14]:
cardiovascular_kidney = pd.merge(cardiovascular, kidney, on='menu_title')
cardiovascular_kidney.head()

,menu_title,positive-cardiovascular,negative-cardiovascular,very_negative-cardiovascular,neutral-cardiovascular,reasoning-cardiovascular,positive-kidney,negative-kidney,very_negative-kidney,neutral-kidney,reasoning-kidney
0,Easy Chicken Fajita Marinade,6,2,0,0,honey (negative): A form of added sugar; high ...,3,2,0,0,honey (negative): A source of sugar and potass...
1,Boneless Buffalo Wings,6,3,2,0,hot pepper sauce (negative): Typically very hi...,4,4,2,0,hot pepper sauce (very negative): Typically ex...
2,Vietnamese Aromatic Lamb Chops,8,2,1,0,lime wedge (positive): A whole fruit source of...,5,2,1,0,garlic (positive): Excellent for adding flavor...
3,Joy's Green Banana Salad,8,0,3,0,"banana (positive): Very high in potassium, a k...",4,4,3,0,banana (very negative): Famously high in potas...
4,Danish Christmas Red Cabbage,2,0,2,0,red cabbage (positive): High in fiber and hear...,3,1,1,0,red cabbage (positive): A low-potassium vegeta...

In [15]:
len(cardiovascular_kidney)

1708

In [16]:
cardiovascular_kidney_diabetes = pd.merge(cardiovascular_kidney, diabetes, on='menu_title')
cardiovascular_kidney_diabetes.head()

,menu_title,positive-cardiovascular,negative-cardiovascular,very_negative-cardiovascular,neutral-cardiovascular,reasoning-cardiovascular,positive-kidney,negative-kidney,very_negative-kidney,neutral-kidney,reasoning-kidney,positive-diabetes,negative-diabetes,very_negative-diabetes,neutral-diabetes,reasoning-diabetes
0,Easy Chicken Fajita Marinade,6,2,0,0,honey (negative): A form of added sugar; high ...,3,2,0,0,honey (negative): A source of sugar and potass...,4,0,1,0,honey (very negative): A form of simple sugar ...
1,Boneless Buffalo Wings,6,3,2,0,hot pepper sauce (negative): Typically very hi...,4,4,2,0,hot pepper sauce (very negative): Typically ex...,4,3,2,0,hot pepper sauce (negative): Often very high i...
2,Vietnamese Aromatic Lamb Chops,8,2,1,0,lime wedge (positive): A whole fruit source of...,5,2,1,0,garlic (positive): Excellent for adding flavor...,7,1,1,0,garlic (positive): May improve cardiovascular ...
3,Joy's Green Banana Salad,8,0,3,0,"banana (positive): Very high in potassium, a k...",4,4,3,0,banana (very negative): Famously high in potas...,7,2,2,0,banana (negative): Higher in sugar and carbohy...
4,Danish Christmas Red Cabbage,2,0,2,0,red cabbage (positive): High in fiber and hear...,3,1,1,0,red cabbage (positive): A low-potassium vegeta...,3,1,1,0,"red cabbage (positive): A low-carbohydrate, hi..."

In [17]:
len(cardiovascular_kidney_diabetes)

1708

In [18]:
allrecipes = pd.read_csv('all_recipes.csv')

In [19]:
len(allrecipes)

1708

In [20]:
allrecipes.columns

Index(['title', 'url', 'servings', 'prepTime', 'cookTime', 'totalTime',
       'ingredients', 'directions', 'nutrition_calories',
       'nutrition_total_fat', 'nutrition_saturated_fat',
       'nutrition_cholesterol', 'nutrition_sodium',
       'nutrition_total_carbohydrate', 'nutrition_dietary_fiber',
       'nutrition_total_sugars', 'nutrition_protein', 'nutrition_vitamin_c',
       'nutrition_calcium', 'nutrition_iron', 'nutrition_potassium'],
      dtype='object')

In [21]:
allrecipes.rename(columns={'title': 'menu_title'}, inplace=True)

In [22]:
allrecipes.head()

,menu_title,url,servings,prepTime,cookTime,totalTime,ingredients,directions,nutrition_calories,nutrition_total_fat,...,nutrition_cholesterol,nutrition_sodium,nutrition_total_carbohydrate,nutrition_dietary_fiber,nutrition_total_sugars,nutrition_protein,nutrition_vitamin_c,nutrition_calcium,nutrition_iron,nutrition_potassium
0,Easy Chicken Fajita Marinade,https://www.allrecipes.com/recipe/231174/easy-...,10,15m,20m,4h 35m,0.5 cup vegetable oil | 2 tablespoons chili po...,2. Gather the ingredients. | 3. Whisk vegetabl...,260kcal,14g,...,70mg,74mg,6g,1g,4g,27g,2mg,19mg,1mg,229mg
1,Boneless Buffalo Wings,https://www.allrecipes.com/recipe/151266/bonel...,6,10m,20m,50m,oil for deep frying | 1 cup unbleached all-pur...,2. Gather all ingredients and heat oil in a de...,710kcal,47g,...,136mg,2335mg,44g,2g,4g,28g,15mg,131mg,4mg,389mg
2,Vietnamese Aromatic Lamb Chops,https://www.allrecipes.com/recipe/152156/vietn...,5,10m,20m,8h 30m,15 (3 ounce) lamb loin chops (1-inch thick) | ...,2. Place lamb chops into a roasting pan; seaso...,555kcal,40g,...,151mg,301mg,7g,1g,5g,39g,7mg,41mg,3mg,545mg
3,Joy&#39;s Green Banana Salad,https://www.allrecipes.com/recipe/60908/joys-g...,6,20m,30m,50m,6 small unripe (green) bananas | 2 tablespoons...,2. Bring a large pot of water to a boil. Cut t...,217kcal,7g,...,81mg,136mg,31g,1g,2g,11g,32mg,71mg,1mg,227mg
4,Danish Christmas Red Cabbage,https://www.allrecipes.com/recipe/79136/danish...,12,30m,1h 0m,1h 30m,"1 small head red cabbage, cored and shredded |...",2. Place cabbage in a large saucepan. Add wate...,144kcal,0g,...,not provided,402mg,37g,1g,35g,1g,27mg,24mg,0mg,116mg

In [23]:
len(allrecipes)

1708

In [24]:
unique_menu_titles = allrecipes['menu_title'].unique()
unique_menu_titles

array(['Easy Chicken Fajita Marinade', 'Boneless Buffalo Wings',
       'Vietnamese Aromatic Lamb Chops', ...,
       'Gheymeh (Persian Beef Stew)', 'Spicy Tuna Sushi Roll',
       'Hawaiian Bread I'], shape=(1708,), dtype=object)

In [25]:
len(unique_menu_titles)

1708

In [26]:
unique_menu_titles = cardiovascular_kidney_diabetes['menu_title'].unique()
unique_menu_titles

array(['Easy Chicken Fajita Marinade', 'Boneless Buffalo Wings',
       'Vietnamese Aromatic Lamb Chops', ...,
       'Gheymeh (Persian Beef Stew)', 'Spicy Tuna Sushi Roll',
       'Hawaiian Bread I'], shape=(1708,), dtype=object)

In [27]:
len(unique_menu_titles)

1708

In [28]:
allrecipes.columns

Index(['menu_title', 'url', 'servings', 'prepTime', 'cookTime', 'totalTime',
       'ingredients', 'directions', 'nutrition_calories',
       'nutrition_total_fat', 'nutrition_saturated_fat',
       'nutrition_cholesterol', 'nutrition_sodium',
       'nutrition_total_carbohydrate', 'nutrition_dietary_fiber',
       'nutrition_total_sugars', 'nutrition_protein', 'nutrition_vitamin_c',
       'nutrition_calcium', 'nutrition_iron', 'nutrition_potassium'],
      dtype='object')

In [29]:
import html

# Apply html.unescape to the 'menu_title' column
allrecipes['menu_title'] = allrecipes['menu_title'].apply(html.unescape)

# Write the updated DataFrame back to the file
#allrecipes.to_csv('all_recipes.csv', index=False)

In [30]:
allrecipes.columns

Index(['menu_title', 'url', 'servings', 'prepTime', 'cookTime', 'totalTime',
       'ingredients', 'directions', 'nutrition_calories',
       'nutrition_total_fat', 'nutrition_saturated_fat',
       'nutrition_cholesterol', 'nutrition_sodium',
       'nutrition_total_carbohydrate', 'nutrition_dietary_fiber',
       'nutrition_total_sugars', 'nutrition_protein', 'nutrition_vitamin_c',
       'nutrition_calcium', 'nutrition_iron', 'nutrition_potassium'],
      dtype='object')

In [31]:
cardiovascular_kidney_diabetes['menu_title'] = cardiovascular_kidney_diabetes['menu_title'].apply(html.unescape)

# Write the updated DataFrame back to the file
#cardiovascular_kidney_diabetes.to_csv('cardiovascular_kidney_diabetes.csv', index=False)

In [32]:
cardiovascular_kidney_diabetes.columns

Index(['menu_title', 'positive-cardiovascular', 'negative-cardiovascular',
       'very_negative-cardiovascular', 'neutral-cardiovascular',
       'reasoning-cardiovascular', 'positive-kidney', 'negative-kidney',
       'very_negative-kidney', 'neutral-kidney', 'reasoning-kidney',
       'positive-diabetes', 'negative-diabetes', 'very_negative-diabetes',
       'neutral-diabetes', 'reasoning-diabetes'],
      dtype='object')

In [33]:
recipes = pd.merge(allrecipes, cardiovascular_kidney_diabetes, on='menu_title')
recipes.head()

,menu_title,url,servings,prepTime,cookTime,totalTime,ingredients,directions,nutrition_calories,nutrition_total_fat,...,positive-kidney,negative-kidney,very_negative-kidney,neutral-kidney,reasoning-kidney,positive-diabetes,negative-diabetes,very_negative-diabetes,neutral-diabetes,reasoning-diabetes
0,Easy Chicken Fajita Marinade,https://www.allrecipes.com/recipe/231174/easy-...,10,15m,20m,4h 35m,0.5 cup vegetable oil | 2 tablespoons chili po...,2. Gather the ingredients. | 3. Whisk vegetabl...,260kcal,14g,...,3,2,0,0,honey (negative): A source of sugar and potass...,4,0,1,0,honey (very negative): A form of simple sugar ...
1,Boneless Buffalo Wings,https://www.allrecipes.com/recipe/151266/bonel...,6,10m,20m,50m,oil for deep frying | 1 cup unbleached all-pur...,2. Gather all ingredients and heat oil in a de...,710kcal,47g,...,4,4,2,0,hot pepper sauce (very negative): Typically ex...,4,3,2,0,hot pepper sauce (negative): Often very high i...
2,Vietnamese Aromatic Lamb Chops,https://www.allrecipes.com/recipe/152156/vietn...,5,10m,20m,8h 30m,15 (3 ounce) lamb loin chops (1-inch thick) | ...,2. Place lamb chops into a roasting pan; seaso...,555kcal,40g,...,5,2,1,0,garlic (positive): Excellent for adding flavor...,7,1,1,0,garlic (positive): May improve cardiovascular ...
3,Joy's Green Banana Salad,https://www.allrecipes.com/recipe/60908/joys-g...,6,20m,30m,50m,6 small unripe (green) bananas | 2 tablespoons...,2. Bring a large pot of water to a boil. Cut t...,217kcal,7g,...,4,4,3,0,banana (very negative): Famously high in potas...,7,2,2,0,banana (negative): Higher in sugar and carbohy...
4,Danish Christmas Red Cabbage,https://www.allrecipes.com/recipe/79136/danish...,12,30m,1h 0m,1h 30m,"1 small head red cabbage, cored and shredded |...",2. Place cabbage in a large saucepan. Add wate...,144kcal,0g,...,3,1,1,0,red cabbage (positive): A low-potassium vegeta...,3,1,1,0,"red cabbage (positive): A low-carbohydrate, hi..."

In [34]:
len(recipes)

1696

In [35]:
recipes.columns

Index(['menu_title', 'url', 'servings', 'prepTime', 'cookTime', 'totalTime',
       'ingredients', 'directions', 'nutrition_calories',
       'nutrition_total_fat', 'nutrition_saturated_fat',
       'nutrition_cholesterol', 'nutrition_sodium',
       'nutrition_total_carbohydrate', 'nutrition_dietary_fiber',
       'nutrition_total_sugars', 'nutrition_protein', 'nutrition_vitamin_c',
       'nutrition_calcium', 'nutrition_iron', 'nutrition_potassium',
       'positive-cardiovascular', 'negative-cardiovascular',
       'very_negative-cardiovascular', 'neutral-cardiovascular',
       'reasoning-cardiovascular', 'positive-kidney', 'negative-kidney',
       'very_negative-kidney', 'neutral-kidney', 'reasoning-kidney',
       'positive-diabetes', 'negative-diabetes', 'very_negative-diabetes',
       'neutral-diabetes', 'reasoning-diabetes'],
      dtype='object')

In [36]:
len(recipes)

1696

In [37]:
recipes['score_cardiovascular'] = (
    recipes['positive-cardiovascular'] - recipes['negative-cardiovascular'] - (2 * recipes['very_negative-cardiovascular'])
) / (
    recipes['positive-cardiovascular'] + recipes['negative-cardiovascular'] + recipes['very_negative-cardiovascular']
)

In [38]:
recipes.head()

,menu_title,url,servings,prepTime,cookTime,totalTime,ingredients,directions,nutrition_calories,nutrition_total_fat,...,negative-kidney,very_negative-kidney,neutral-kidney,reasoning-kidney,positive-diabetes,negative-diabetes,very_negative-diabetes,neutral-diabetes,reasoning-diabetes,score_cardiovascular
0,Easy Chicken Fajita Marinade,https://www.allrecipes.com/recipe/231174/easy-...,10,15m,20m,4h 35m,0.5 cup vegetable oil | 2 tablespoons chili po...,2. Gather the ingredients. | 3. Whisk vegetabl...,260kcal,14g,...,2,0,0,honey (negative): A source of sugar and potass...,4,0,1,0,honey (very negative): A form of simple sugar ...,0.500000
1,Boneless Buffalo Wings,https://www.allrecipes.com/recipe/151266/bonel...,6,10m,20m,50m,oil for deep frying | 1 cup unbleached all-pur...,2. Gather all ingredients and heat oil in a de...,710kcal,47g,...,4,2,0,hot pepper sauce (very negative): Typically ex...,4,3,2,0,hot pepper sauce (negative): Often very high i...,-0.090909
2,Vietnamese Aromatic Lamb Chops,https://www.allrecipes.com/recipe/152156/vietn...,5,10m,20m,8h 30m,15 (3 ounce) lamb loin chops (1-inch thick) | ...,2. Place lamb chops into a roasting pan; seaso...,555kcal,40g,...,2,1,0,garlic (positive): Excellent for adding flavor...,7,1,1,0,garlic (positive): May improve cardiovascular ...,0.363636
3,Joy's Green Banana Salad,https://www.allrecipes.com/recipe/60908/joys-g...,6,20m,30m,50m,6 small unripe (green) bananas | 2 tablespoons...,2. Bring a large pot of water to a boil. Cut t...,217kcal,7g,...,4,3,0,banana (very negative): Famously high in potas...,7,2,2,0,banana (negative): Higher in sugar and carbohy...,0.181818
4,Danish Christmas Red Cabbage,https://www.allrecipes.com/recipe/79136/danish...,12,30m,1h 0m,1h 30m,"1 small head red cabbage, cored and shredded |...",2. Place cabbage in a large saucepan. Add wate...,144kcal,0g,...,1,1,0,red cabbage (positive): A low-potassium vegeta...,3,1,1,0,"red cabbage (positive): A low-carbohydrate, hi...",-0.500000

In [39]:
recipes['score_diabetes'] = (
    recipes['positive-diabetes'] - recipes['negative-diabetes'] - (2 * recipes['very_negative-diabetes'])
) / (
    recipes['positive-diabetes'] + recipes['negative-diabetes'] + recipes['very_negative-diabetes']
)

In [40]:
recipes.head()

,menu_title,url,servings,prepTime,cookTime,totalTime,ingredients,directions,nutrition_calories,nutrition_total_fat,...,very_negative-kidney,neutral-kidney,reasoning-kidney,positive-diabetes,negative-diabetes,very_negative-diabetes,neutral-diabetes,reasoning-diabetes,score_cardiovascular,score_diabetes
0,Easy Chicken Fajita Marinade,https://www.allrecipes.com/recipe/231174/easy-...,10,15m,20m,4h 35m,0.5 cup vegetable oil | 2 tablespoons chili po...,2. Gather the ingredients. | 3. Whisk vegetabl...,260kcal,14g,...,0,0,honey (negative): A source of sugar and potass...,4,0,1,0,honey (very negative): A form of simple sugar ...,0.500000,0.400000
1,Boneless Buffalo Wings,https://www.allrecipes.com/recipe/151266/bonel...,6,10m,20m,50m,oil for deep frying | 1 cup unbleached all-pur...,2. Gather all ingredients and heat oil in a de...,710kcal,47g,...,2,0,hot pepper sauce (very negative): Typically ex...,4,3,2,0,hot pepper sauce (negative): Often very high i...,-0.090909,-0.333333
2,Vietnamese Aromatic Lamb Chops,https://www.allrecipes.com/recipe/152156/vietn...,5,10m,20m,8h 30m,15 (3 ounce) lamb loin chops (1-inch thick) | ...,2. Place lamb chops into a roasting pan; seaso...,555kcal,40g,...,1,0,garlic (positive): Excellent for adding flavor...,7,1,1,0,garlic (positive): May improve cardiovascular ...,0.363636,0.444444
3,Joy's Green Banana Salad,https://www.allrecipes.com/recipe/60908/joys-g...,6,20m,30m,50m,6 small unripe (green) bananas | 2 tablespoons...,2. Bring a large pot of water to a boil. Cut t...,217kcal,7g,...,3,0,banana (very negative): Famously high in potas...,7,2,2,0,banana (negative): Higher in sugar and carbohy...,0.181818,0.090909
4,Danish Christmas Red Cabbage,https://www.allrecipes.com/recipe/79136/danish...,12,30m,1h 0m,1h 30m,"1 small head red cabbage, cored and shredded |...",2. Place cabbage in a large saucepan. Add wate...,144kcal,0g,...,1,0,red cabbage (positive): A low-potassium vegeta...,3,1,1,0,"red cabbage (positive): A low-carbohydrate, hi...",-0.500000,0.000000

In [41]:
recipes['score_kidney'] = (
    recipes['positive-kidney'] - recipes['negative-kidney'] - (2 * recipes['very_negative-kidney'])
) / (
    recipes['positive-kidney'] + recipes['negative-kidney'] + recipes['very_negative-kidney']
)

In [42]:
recipes.head()

,menu_title,url,servings,prepTime,cookTime,totalTime,ingredients,directions,nutrition_calories,nutrition_total_fat,...,neutral-kidney,reasoning-kidney,positive-diabetes,negative-diabetes,very_negative-diabetes,neutral-diabetes,reasoning-diabetes,score_cardiovascular,score_diabetes,score_kidney
0,Easy Chicken Fajita Marinade,https://www.allrecipes.com/recipe/231174/easy-...,10,15m,20m,4h 35m,0.5 cup vegetable oil | 2 tablespoons chili po...,2. Gather the ingredients. | 3. Whisk vegetabl...,260kcal,14g,...,0,honey (negative): A source of sugar and potass...,4,0,1,0,honey (very negative): A form of simple sugar ...,0.500000,0.400000,0.200000
1,Boneless Buffalo Wings,https://www.allrecipes.com/recipe/151266/bonel...,6,10m,20m,50m,oil for deep frying | 1 cup unbleached all-pur...,2. Gather all ingredients and heat oil in a de...,710kcal,47g,...,0,hot pepper sauce (very negative): Typically ex...,4,3,2,0,hot pepper sauce (negative): Often very high i...,-0.090909,-0.333333,-0.400000
2,Vietnamese Aromatic Lamb Chops,https://www.allrecipes.com/recipe/152156/vietn...,5,10m,20m,8h 30m,15 (3 ounce) lamb loin chops (1-inch thick) | ...,2. Place lamb chops into a roasting pan; seaso...,555kcal,40g,...,0,garlic (positive): Excellent for adding flavor...,7,1,1,0,garlic (positive): May improve cardiovascular ...,0.363636,0.444444,0.125000
3,Joy's Green Banana Salad,https://www.allrecipes.com/recipe/60908/joys-g...,6,20m,30m,50m,6 small unripe (green) bananas | 2 tablespoons...,2. Bring a large pot of water to a boil. Cut t...,217kcal,7g,...,0,banana (very negative): Famously high in potas...,7,2,2,0,banana (negative): Higher in sugar and carbohy...,0.181818,0.090909,-0.545455
4,Danish Christmas Red Cabbage,https://www.allrecipes.com/recipe/79136/danish...,12,30m,1h 0m,1h 30m,"1 small head red cabbage, cored and shredded |...",2. Place cabbage in a large saucepan. Add wate...,144kcal,0g,...,0,red cabbage (positive): A low-potassium vegeta...,3,1,1,0,"red cabbage (positive): A low-carbohydrate, hi...",-0.500000,0.000000,0.000000

In [43]:
len(recipes)

1696

In [44]:
recipes.to_csv('recipes.csv', index=False)